name: Sync fork with upstream

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: bia-pain-bache/BPB-Worker-Panel
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            .github/workflows/sync.yml

      - name: Check for errors
        if: failure()
        run: echo "Sync failed! Please check the logs for more details."

      - name: Sync success message
        if: success()
        run: echo "Sync completed successfully!"
